sources:
  - name: jaffle_shop
    database: jaffle_raw
    schema: jaffle_shop
    tables:
      - name: orders
      - name: customers
  - name: stripe
    database: jaffle_raw
    schema: stripe
    tables:
      - name: payments